last

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -14,7 +14,6 @@ env:
   HTACCESS_PATH: /var/www/clients/client0/web3/web/symblog/public/
   BACKUP_DIR: /var/www/clients/client0/web3/web/backups
   BACKUP_FILE: /var/www/clients/client0/web3/web/backups/symblog_backup.tar.gz
-  FILTER_FILE: /var/www/clients/client0/web3/web/symblog/.tar-filter
   DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
   DATE: date +%F_%T
 
@@ -74,11 +73,11 @@ jobs:
       - name: Backup Source Code and Templates
         run: |
           ssh deploy << EOF
-          echo "Contenu du fichier de filtre :"
-          cat "${FILTER_FILE}"
           if [ -d "/var/www/clients/client0/web3/web/symblog" ]; then
             echo "Backing up ..."
-            tar -czf "${BACKUP_FILE}" --exclude-from="${FILTER_FILE}" -C "${DEST_DIR}" .
+            tar -czf "${BACKUP_FILE}" \
+             --exclude="var/cache" \
+             -C "${DEST_DIR}" .
 
             # Vérifier que la sauvegarde a été créée
             if [ -f "${BACKUP_FILE}" ]; then
@@ -103,7 +102,7 @@ jobs:
             --exclude='.env' \
             ./ deploy:$DEST_DIR/
 
-      #failed because IP response 403
+      #failed because github IP not in authorized IP
       #- name: Validate Deployment
       #  run: |
       #    RESPONSE=$(curl -L -s -o /dev/null -w "%{http_code}" "https://testartep.org/symblog")
@@ -115,7 +114,7 @@ jobs:
 
       - name: Update Dependencies and Clear Cache
         run: |
-          ssh deploy << EOF
+          ssh deploy << 'EOF'
           cd "$DEST_DIR" && {
             echo "Clearing cache..."
             php bin/console cache:clear
@@ -128,7 +127,7 @@ jobs:
         run: |
           ssh deploy << 'EOF'
           cd "$DEST_DIR" && {
-            git fetch --unshallow || true
+            git fetch origin
             if git diff --name-only origin/main | grep -q "composer.lock"; then
               echo "Composer.lock changed, installing dependencies..."
               composer install --no-dev --optimize-autoloader
@@ -155,8 +154,16 @@ jobs:
         if: failure()
         run: |
           ssh deploy << EOF
-          echo "Rolling back source code and templates..."
-          tar -xzf "/var/www/clients/client0/web3/web/backups/symblog_backup.tar.gz" -C "$DEST_DIR"
+            if [ -f "${BACKUP_FILE}" ]; then
+              echo "Rolling back source code and templates..."
+              tar -xzf "${BACKUP_FILE}" -C "${DEST_DIR}"
+              echo "Clearing cache..."
+              php bin/console cache:clear
+              php bin/console cache:warmup
+            else
+              echo "No backup file found. Cannot rollback."
+              exit 1
+            fi
           EOF
 
       - name: Disable Maintenance Mode
@@ -173,10 +180,10 @@ jobs:
           fi
           EOF
 
-      #- name: Cleanup Old Backups
-      #  if: always()
-      #  run: |
-      #    ssh deploy << EOF
-      #    find "$BACKUP_DIR" -type f -name "db_backup.sql" -delete
-      #    find "$BACKUP_DIR" -type f -name "src_templates_backup.tar.gz" -delete
-      #    EOF
+      - name: Cleanup Old Backups
+        if: always()
+        run: |
+          ssh deploy << EOF
+          find "$BACKUP_DIR" -type f -name "db_backup.sql" -delete
+          find "$BACKUP_DIR" -type f -name "src_templates_backup.tar.gz" -delete
+          EOF
