fsdfds

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -102,19 +102,22 @@ jobs:
             --exclude='.env' \
             ./ deploy:$DEST_DIR/
 
-      - name: Validate Deployment
-        run: |
-          RESPONSE=$(curl -L -s -o /dev/null -w "%{http_code}" "https://testartep.org/symblog")
-          if [[ "$RESPONSE" -ne 200 ]]; then
-            echo "Application is not responding! HTTP Status: $RESPONSE"
-            exit 1
-          fi
-          echo "Deployment successful! HTTP Status: $RESPONSE"
+      #failed because IP response 403
+      #- name: Validate Deployment
+      #  run: |
+      #    RESPONSE=$(curl -L -s -o /dev/null -w "%{http_code}" "https://testartep.org/symblog")
+      #    if [[ "$RESPONSE" -ne 200 ]]; then
+      #      echo "Application is not responding! HTTP Status: $RESPONSE"
+      #      exit 1
+      #    fi
+      #    echo "Deployment successful! HTTP Status: $RESPONSE"
 
       - name: Update Dependencies and Clear Cache
         run: |
           ssh deploy << 'EOF'
           cd "$DEST_DIR"
+          echo "Updating dependencies and clearing cache..."
+          #composer install --no-dev --optimize-autoloader
           php bin/console cache:clear
           php bin/console cache:warmup
           composer dump-autoload --optimize
@@ -126,7 +129,10 @@ jobs:
           cd "$DEST_DIR"
           git fetch --unshallow || true
           if git diff --name-only origin/main | grep -q "composer.lock"; then
+            echo "Composer.lock changed, installing dependencies..."
             composer install --no-dev --optimize-autoloader
+          else
+            echo "No Composer changes detected, skipping install."
           fi
           EOF
 
@@ -135,7 +141,10 @@ jobs:
           ssh deploy << 'EOF'
           cd "$DEST_DIR"
           if php bin/console doctrine:migrations:status -no-ansi | grep -q "New Migrations"; then
+            echo "New migrations found, running migrations..."
             php bin/console doctrine:migrations:migrate --no-interaction
+          else
+            echo "No new migrations detected."
           fi
           EOF
 
@@ -143,6 +152,7 @@ jobs:
         if: failure()
         run: |
           ssh deploy << EOF
+          echo "Rolling back source code and templates..."
           tar -xzf "/var/www/clients/client0/web3/web/backups/src_templates_backup.tar.gz" -C "$DEST_DIR"
           EOF
 
